# myapp-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
spec:
  selector:
    app: {{ include "myapp-chart.name" . }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
